<?php

namespace App\Http\Requests;

use Illuminate\Contracts\Validation\Validator;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Http\JsonResponse;

class CommodityPost extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            //
            'id'=>'nullable|integer',
            'title'=>'required|',
            'price'=>'required|numeric',
            'description'=>'required',
            'detail'=>'required|min:50|max:300',
            'phone'=>'required',
            'latitude'=>'required|numeric',
            'longitude'=>'required|numeric'
        ];
    }
    public function messages()
    {
        return [
            'title.required'=>'标题不能为空！',
            'price.required'=>'价格不能为空！',
            'phone.required'=>'手机号不能为空',
            'description.required'=>'基本详情不能为空！',
            'detail.required'=>'更多详情不能为空！',
            'detail.min'=>'更多详情最少50个字符！',
            'detail.mix'=>'更多详情最多不能超过300个字符！',
            'latitude.required'=>'位置信息不能为空！',
            'latitude.numeric'=>'位置信息格式不正确！',
            'longitude.required'=>'位置信息不能为空！',
            'longitude.numeric'=>'位置信息格式不正确！'
        ];
    }
    protected function formatErrors(Validator $validator)
    {
        $message = $validator->errors()->first();
        return [$message]; // TODO: Change the autogenerated stub
    }
    public function response(array $errors)
    {
        return new JsonResponse([
            'return_msg'=>$errors[0],
            'return_code'=>'FAIL'
        ]);
    }
}
