<?php

namespace App\Http\Requests;

use Illuminate\Contracts\Validation\Validator;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Http\JsonResponse;

class CommodityPost extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            //
            'id'=>'nullable|integer',
            'title'=>'required|',
            'price'=>'required|numeric',
            'description'=>'nullable',
            'phone'=>'required|',
        ];
//        $table->increments('id');
//        $table->string('title');
//        $table->tinyInteger('area_id');
//        $table->float('price')->default(0);
//        $table->text('description');
//        $table->tinyInteger('category_id');
//        $table->tinyInteger('state');
//        $table->text('detail');
//        $table->string('phone');
//        $table->string('QQ');
//        $table->string('WeChat');
    }
    public function messages()
    {
        return [
            'title.required'=>'标题不能为空！',
            'price.required'=>'价格不能为空！',
            'phone.required'=>'手机号不能为空'
        ];
    }
    protected function formatErrors(Validator $validator)
    {
        $message = $validator->errors()->first();
        return [$message]; // TODO: Change the autogenerated stub
    }
    public function response(array $errors)
    {
        return new JsonResponse([
            'return_msg'=>$errors[0],
            'return_code'=>'FAIL'
        ], 422);
    }
}
