<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Http\JsonResponse;
use Illuminate\Contracts\Validation\Validator;

class FilterPost extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            //
            'latitude'=>'required|numeric',
            'longitude'=>'required|numeric',
            'radius'=>'required|numeric',
        ];
    }
    public function messages()
    {
        return [
            'latitude.numeric'=>'位置信息不能为空！',
            'latitude.required'=>'位置信息格式错误！',
            'longitude.numeric'=>'位置信息不能为空！',
            'longitude.required'=>'位置信息格式错误！',
            'radius.numeric'=>'距离不能为空！',
            'radius.required'=>'距离格式错误！'
        ];
    }
    protected function formatErrors(Validator $validator)
    {
        $message = $validator->errors()->first();
        return [$message]; // TODO: Change the autogenerated stub
    }
    public function response(array $errors)
    {
        return new JsonResponse([
            'return_msg'=>$errors[0],
            'return_code'=>'FAIL'
        ]);
    }
}
