<?php

namespace App\Http\Requests;

use Illuminate\Contracts\Validation\Validator;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Http\JsonResponse;

class RejectPost extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            //
            'report_id'=>'required',
            'detail'=>'required|max:255',
            'phone'=>'required',
        ];
    }
    public function messages()
    {
        return [
            'report_id.required'=>'参数不能为空！',
            'detail.required'=>'描述不能为空！',
            'phone.required'=>'手机号不能为空！',
            'detail.max'=>'描述不能超过255个字符'
        ];
    }
    protected function formatErrors(Validator $validator)
    {
        $message = $validator->errors()->first();
        return [$message]; // TODO: Change the autogenerated stub
    }
    public function response(array $errors)
    {
        return new JsonResponse([
            'return_msg'=>$errors[0],
            'return_code'=>'FAIL'
        ]);
    }
}
